services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      # - ~/github/clowa:/data
      - .:/data
    environment:
      - POSTGRES_SERVICE_URL=postgresql://dbuser:${TSDB_PASSWORD}@db:5432/llama-vector
      - OLLAMA_SERVICE_URL=http://ollama:11434
    depends_on:
      - ollama
      - db

  ollama:
    image: ollama/ollama:0.5.4
    # build:
    #   context: ollama
    #   dockerfile: Dockerfile
    # ports:
    #   - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama

  db:
    # image: pgvector/pgvector:pg17
    image: timescale/timescaledb:latest-pg17-oss
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=llama-vector
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=${TSDB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
