version: "3.6"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ~/github/clowa:/data
    depends_on:
      - ollama
      - db

  ollama:
    image: ollama/ollama:0.5.4
    # ports:
    #   - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama

  db:
    image: timescale/timescaledb:2.17.2-pg17-oss
    # image: timescale/timescaledb:latest-pg17-oss
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
